### ISSUE TITLE
A few errors when running setup.sh on webshop

### ISSUE THREAD

**Issue by jpiabrantes** [WooooDyy/AgentGym#22]
I followed the readme.md and run:
```sh
conda env create -n agentenv-webshop -f environment.yml
conda activate agentenv-webshop
bash ./setup.sh
```

Here are the errors when running ./setup.sh:
<details>

```sh
The following packages will be UPDATED:

  openjdk                                11.0.21-h4260e57_0 --> 11.0.23-h24d6bf4_0 

The following packages will be DOWNGRADED:

  alsa-lib                                1.2.12-h4ab18f5_0 --> 1.2.11-hd590300_1 


Proceed ([y]/n)? 


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Traceback (most recent call last):
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 8, in init spacy.pipeline.pipe
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/spacy/training/__init__.py", line 11, in <module>
    from .callbacks import create_copy_from_base_model  # noqa: F401
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/spacy/training/callbacks.py", line 3, in <module>
    from ..language import Language
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/spacy/language.py", line 25, in <module>
    from .training.initialize import init_vocab, init_tok2vec
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/spacy/training/initialize.py", line 14, in <module>
    from .pretrain import get_tok2vec_ref
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/spacy/training/pretrain.py", line 16, in <module>
    from ..schemas import ConfigSchemaPretrain
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/spacy/schemas.py", line 216, in <module>
    class TokenPattern(BaseModel):
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 451, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 545, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 550, in pydantic.fields.ModelField._type_analysis
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "convert_product_file_format.py", line 7, in <module>
    from web_agent_site.engine.engine import load_products
  File "/home/joaoabrantis/qd/AgentGym/agentenv-webshop/webshop/search_engine/../web_agent_site/engine/engine.py", line 16, in <module>
    from pyserini.search.lucene import LuceneSearcher
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/pyserini/search/__init__.py", line 19, in <module>
    from .lucene import JLuceneSearcherResult, LuceneSimilarities, LuceneFusionSearcher, LuceneSearcher
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/pyserini/search/lucene/__init__.py", line 18, in <module>
    from ._impact_searcher import JImpactSearcherResult, LuceneImpactSearcher
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/pyserini/search/lucene/_impact_searcher.py", line 28, in <module>
    from pyserini.encode import QueryEncoder, TokFreqQueryEncoder, UniCoilQueryEncoder, \
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/pyserini/encode/__init__.py", line 17, in <module>
    from ._base import DocumentEncoder, QueryEncoder, JsonlCollectionIterator,\
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/pyserini/encode/_base.py", line 19, in <module>
    import faiss
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/faiss/__init__.py", line 16, in <module>
    from .loader import *
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: numpy.core.multiarray failed to import
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2024-06-19 10:54:55,992 INFO  [main] index.IndexCollection (IndexCollection.java:645) - Setting log level to INFO
2024-06-19 10:54:55,993 INFO  [main] index.IndexCollection (IndexCollection.java:648) - Starting indexer...
2024-06-19 10:54:55,993 INFO  [main] index.IndexCollection (IndexCollection.java:649) - ============ Loading Parameters ============
2024-06-19 10:54:55,993 INFO  [main] index.IndexCollection (IndexCollection.java:650) - DocumentCollection path: resources_100
2024-06-19 10:54:55,993 INFO  [main] index.IndexCollection (IndexCollection.java:651) - CollectionClass: JsonCollection
2024-06-19 10:54:55,994 INFO  [main] index.IndexCollection (IndexCollection.java:652) - Generator: DefaultLuceneDocumentGenerator
2024-06-19 10:54:55,994 INFO  [main] index.IndexCollection (IndexCollection.java:653) - Threads: 1
2024-06-19 10:54:55,994 INFO  [main] index.IndexCollection (IndexCollection.java:654) - Language: en
2024-06-19 10:54:55,994 INFO  [main] index.IndexCollection (IndexCollection.java:655) - Stemmer: porter
2024-06-19 10:54:55,994 INFO  [main] index.IndexCollection (IndexCollection.java:656) - Keep stopwords? false
2024-06-19 10:54:55,994 INFO  [main] index.IndexCollection (IndexCollection.java:657) - Stopwords: null
2024-06-19 10:54:55,994 INFO  [main] index.IndexCollection (IndexCollection.java:658) - Store positions? true
2024-06-19 10:54:55,994 INFO  [main] index.IndexCollection (IndexCollection.java:659) - Store docvectors? true
2024-06-19 10:54:55,994 INFO  [main] index.IndexCollection (IndexCollection.java:660) - Store document "contents" field? false
2024-06-19 10:54:55,995 INFO  [main] index.IndexCollection (IndexCollection.java:661) - Store document "raw" field? true
2024-06-19 10:54:55,995 INFO  [main] index.IndexCollection (IndexCollection.java:662) - Additional fields to index: []
2024-06-19 10:54:55,995 INFO  [main] index.IndexCollection (IndexCollection.java:663) - Optimize (merge segments)? false
2024-06-19 10:54:55,995 INFO  [main] index.IndexCollection (IndexCollection.java:664) - Whitelist: null
2024-06-19 10:54:55,995 INFO  [main] index.IndexCollection (IndexCollection.java:665) - Pretokenized?: false
2024-06-19 10:54:55,995 INFO  [main] index.IndexCollection (IndexCollection.java:685) - Directly building Lucene indexes...
2024-06-19 10:54:55,995 INFO  [main] index.IndexCollection (IndexCollection.java:686) - Index path: indexes_100
2024-06-19 10:54:55,996 INFO  [main] index.IndexCollection (IndexCollection.java:741) - ============ Indexing Collection ============
2024-06-19 10:54:56,109 INFO  [main] index.IndexCollection (IndexCollection.java:845) - Thread pool with 1 threads initialized.
2024-06-19 10:54:56,110 INFO  [main] index.IndexCollection (IndexCollection.java:847) - Initializing collection in resources_100
2024-06-19 10:54:56,111 INFO  [main] index.IndexCollection (IndexCollection.java:856) - 0 files found
2024-06-19 10:54:56,111 INFO  [main] index.IndexCollection (IndexCollection.java:857) - Starting to index...
2024-06-19 10:54:56,120 INFO  [main] index.IndexCollection (IndexCollection.java:941) - Indexing Complete! 0 documents indexed
2024-06-19 10:54:56,120 INFO  [main] index.IndexCollection (IndexCollection.java:942) - ============ Final Counter Values ============
2024-06-19 10:54:56,121 INFO  [main] index.IndexCollection (IndexCollection.java:943) - indexed:                0
2024-06-19 10:54:56,121 INFO  [main] index.IndexCollection (IndexCollection.java:944) - unindexable:            0
2024-06-19 10:54:56,121 INFO  [main] index.IndexCollection (IndexCollection.java:945) - empty:                  0
2024-06-19 10:54:56,121 INFO  [main] index.IndexCollection (IndexCollection.java:946) - skipped:                0
2024-06-19 10:54:56,121 INFO  [main] index.IndexCollection (IndexCollection.java:947) - errors:                 0
2024-06-19 10:54:56,124 INFO  [main] index.IndexCollection (IndexCollection.java:950) - Total 0 documents indexed in 00:00:00
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2024-06-19 10:54:56,972 INFO  [main] index.IndexCollection (IndexCollection.java:645) - Setting log level to INFO
2024-06-19 10:54:56,973 INFO  [main] index.IndexCollection (IndexCollection.java:648) - Starting indexer...
2024-06-19 10:54:56,973 INFO  [main] index.IndexCollection (IndexCollection.java:649) - ============ Loading Parameters ============
2024-06-19 10:54:56,974 INFO  [main] index.IndexCollection (IndexCollection.java:650) - DocumentCollection path: resources
2024-06-19 10:54:56,974 INFO  [main] index.IndexCollection (IndexCollection.java:651) - CollectionClass: JsonCollection
2024-06-19 10:54:56,974 INFO  [main] index.IndexCollection (IndexCollection.java:652) - Generator: DefaultLuceneDocumentGenerator
2024-06-19 10:54:56,974 INFO  [main] index.IndexCollection (IndexCollection.java:653) - Threads: 1
2024-06-19 10:54:56,974 INFO  [main] index.IndexCollection (IndexCollection.java:654) - Language: en
2024-06-19 10:54:56,974 INFO  [main] index.IndexCollection (IndexCollection.java:655) - Stemmer: porter
2024-06-19 10:54:56,974 INFO  [main] index.IndexCollection (IndexCollection.java:656) - Keep stopwords? false
2024-06-19 10:54:56,974 INFO  [main] index.IndexCollection (IndexCollection.java:657) - Stopwords: null
2024-06-19 10:54:56,974 INFO  [main] index.IndexCollection (IndexCollection.java:658) - Store positions? true
2024-06-19 10:54:56,975 INFO  [main] index.IndexCollection (IndexCollection.java:659) - Store docvectors? true
2024-06-19 10:54:56,975 INFO  [main] index.IndexCollection (IndexCollection.java:660) - Store document "contents" field? false
2024-06-19 10:54:56,975 INFO  [main] index.IndexCollection (IndexCollection.java:661) - Store document "raw" field? true
2024-06-19 10:54:56,975 INFO  [main] index.IndexCollection (IndexCollection.java:662) - Additional fields to index: []
2024-06-19 10:54:56,975 INFO  [main] index.IndexCollection (IndexCollection.java:663) - Optimize (merge segments)? false
2024-06-19 10:54:56,975 INFO  [main] index.IndexCollection (IndexCollection.java:664) - Whitelist: null
2024-06-19 10:54:56,975 INFO  [main] index.IndexCollection (IndexCollection.java:665) - Pretokenized?: false
2024-06-19 10:54:56,975 INFO  [main] index.IndexCollection (IndexCollection.java:685) - Directly building Lucene indexes...
2024-06-19 10:54:56,975 INFO  [main] index.IndexCollection (IndexCollection.java:686) - Index path: indexes
2024-06-19 10:54:56,976 INFO  [main] index.IndexCollection (IndexCollection.java:741) - ============ Indexing Collection ============
2024-06-19 10:54:57,086 INFO  [main] index.IndexCollection (IndexCollection.java:845) - Thread pool with 1 threads initialized.
2024-06-19 10:54:57,086 INFO  [main] index.IndexCollection (IndexCollection.java:847) - Initializing collection in resources
2024-06-19 10:54:57,087 INFO  [main] index.IndexCollection (IndexCollection.java:856) - 0 files found
2024-06-19 10:54:57,087 INFO  [main] index.IndexCollection (IndexCollection.java:857) - Starting to index...
2024-06-19 10:54:57,096 INFO  [main] index.IndexCollection (IndexCollection.java:941) - Indexing Complete! 0 documents indexed
2024-06-19 10:54:57,096 INFO  [main] index.IndexCollection (IndexCollection.java:942) - ============ Final Counter Values ============
2024-06-19 10:54:57,096 INFO  [main] index.IndexCollection (IndexCollection.java:943) - indexed:                0
2024-06-19 10:54:57,096 INFO  [main] index.IndexCollection (IndexCollection.java:944) - unindexable:            0
2024-06-19 10:54:57,096 INFO  [main] index.IndexCollection (IndexCollection.java:945) - empty:                  0
2024-06-19 10:54:57,096 INFO  [main] index.IndexCollection (IndexCollection.java:946) - skipped:                0
2024-06-19 10:54:57,096 INFO  [main] index.IndexCollection (IndexCollection.java:947) - errors:                 0
2024-06-19 10:54:57,099 INFO  [main] index.IndexCollection (IndexCollection.java:950) - Total 0 documents indexed in 00:00:00
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2024-06-19 10:54:57,892 INFO  [main] index.IndexCollection (IndexCollection.java:645) - Setting log level to INFO
2024-06-19 10:54:57,893 INFO  [main] index.IndexCollection (IndexCollection.java:648) - Starting indexer...
2024-06-19 10:54:57,893 INFO  [main] index.IndexCollection (IndexCollection.java:649) - ============ Loading Parameters ============
2024-06-19 10:54:57,893 INFO  [main] index.IndexCollection (IndexCollection.java:650) - DocumentCollection path: resources_1k
2024-06-19 10:54:57,893 INFO  [main] index.IndexCollection (IndexCollection.java:651) - CollectionClass: JsonCollection
2024-06-19 10:54:57,893 INFO  [main] index.IndexCollection (IndexCollection.java:652) - Generator: DefaultLuceneDocumentGenerator
2024-06-19 10:54:57,893 INFO  [main] index.IndexCollection (IndexCollection.java:653) - Threads: 1
2024-06-19 10:54:57,894 INFO  [main] index.IndexCollection (IndexCollection.java:654) - Language: en
2024-06-19 10:54:57,894 INFO  [main] index.IndexCollection (IndexCollection.java:655) - Stemmer: porter
2024-06-19 10:54:57,894 INFO  [main] index.IndexCollection (IndexCollection.java:656) - Keep stopwords? false
2024-06-19 10:54:57,894 INFO  [main] index.IndexCollection (IndexCollection.java:657) - Stopwords: null
2024-06-19 10:54:57,894 INFO  [main] index.IndexCollection (IndexCollection.java:658) - Store positions? true
2024-06-19 10:54:57,894 INFO  [main] index.IndexCollection (IndexCollection.java:659) - Store docvectors? true
2024-06-19 10:54:57,894 INFO  [main] index.IndexCollection (IndexCollection.java:660) - Store document "contents" field? false
2024-06-19 10:54:57,894 INFO  [main] index.IndexCollection (IndexCollection.java:661) - Store document "raw" field? true
2024-06-19 10:54:57,894 INFO  [main] index.IndexCollection (IndexCollection.java:662) - Additional fields to index: []
2024-06-19 10:54:57,895 INFO  [main] index.IndexCollection (IndexCollection.java:663) - Optimize (merge segments)? false
2024-06-19 10:54:57,895 INFO  [main] index.IndexCollection (IndexCollection.java:664) - Whitelist: null
2024-06-19 10:54:57,895 INFO  [main] index.IndexCollection (IndexCollection.java:665) - Pretokenized?: false
2024-06-19 10:54:57,895 INFO  [main] index.IndexCollection (IndexCollection.java:685) - Directly building Lucene indexes...
2024-06-19 10:54:57,895 INFO  [main] index.IndexCollection (IndexCollection.java:686) - Index path: indexes_1k
2024-06-19 10:54:57,896 INFO  [main] index.IndexCollection (IndexCollection.java:741) - ============ Indexing Collection ============
2024-06-19 10:54:58,007 INFO  [main] index.IndexCollection (IndexCollection.java:845) - Thread pool with 1 threads initialized.
2024-06-19 10:54:58,007 INFO  [main] index.IndexCollection (IndexCollection.java:847) - Initializing collection in resources_1k
2024-06-19 10:54:58,008 INFO  [main] index.IndexCollection (IndexCollection.java:856) - 0 files found
2024-06-19 10:54:58,008 INFO  [main] index.IndexCollection (IndexCollection.java:857) - Starting to index...
2024-06-19 10:54:58,017 INFO  [main] index.IndexCollection (IndexCollection.java:941) - Indexing Complete! 0 documents indexed
2024-06-19 10:54:58,017 INFO  [main] index.IndexCollection (IndexCollection.java:942) - ============ Final Counter Values ============
2024-06-19 10:54:58,017 INFO  [main] index.IndexCollection (IndexCollection.java:943) - indexed:                0
2024-06-19 10:54:58,017 INFO  [main] index.IndexCollection (IndexCollection.java:944) - unindexable:            0
2024-06-19 10:54:58,017 INFO  [main] index.IndexCollection (IndexCollection.java:945) - empty:                  0
2024-06-19 10:54:58,017 INFO  [main] index.IndexCollection (IndexCollection.java:946) - skipped:                0
2024-06-19 10:54:58,017 INFO  [main] index.IndexCollection (IndexCollection.java:947) - errors:                 0
2024-06-19 10:54:58,020 INFO  [main] index.IndexCollection (IndexCollection.java:950) - Total 0 documents indexed in 00:00:00
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2024-06-19 10:54:58,872 INFO  [main] index.IndexCollection (IndexCollection.java:645) - Setting log level to INFO
2024-06-19 10:54:58,873 INFO  [main] index.IndexCollection (IndexCollection.java:648) - Starting indexer...
2024-06-19 10:54:58,873 INFO  [main] index.IndexCollection (IndexCollection.java:649) - ============ Loading Parameters ============
2024-06-19 10:54:58,873 INFO  [main] index.IndexCollection (IndexCollection.java:650) - DocumentCollection path: resources_100k
2024-06-19 10:54:58,874 INFO  [main] index.IndexCollection (IndexCollection.java:651) - CollectionClass: JsonCollection
2024-06-19 10:54:58,874 INFO  [main] index.IndexCollection (IndexCollection.java:652) - Generator: DefaultLuceneDocumentGenerator
2024-06-19 10:54:58,874 INFO  [main] index.IndexCollection (IndexCollection.java:653) - Threads: 1
2024-06-19 10:54:58,874 INFO  [main] index.IndexCollection (IndexCollection.java:654) - Language: en
2024-06-19 10:54:58,874 INFO  [main] index.IndexCollection (IndexCollection.java:655) - Stemmer: porter
2024-06-19 10:54:58,874 INFO  [main] index.IndexCollection (IndexCollection.java:656) - Keep stopwords? false
2024-06-19 10:54:58,874 INFO  [main] index.IndexCollection (IndexCollection.java:657) - Stopwords: null
2024-06-19 10:54:58,874 INFO  [main] index.IndexCollection (IndexCollection.java:658) - Store positions? true
2024-06-19 10:54:58,874 INFO  [main] index.IndexCollection (IndexCollection.java:659) - Store docvectors? true
2024-06-19 10:54:58,874 INFO  [main] index.IndexCollection (IndexCollection.java:660) - Store document "contents" field? false
2024-06-19 10:54:58,875 INFO  [main] index.IndexCollection (IndexCollection.java:661) - Store document "raw" field? true
2024-06-19 10:54:58,875 INFO  [main] index.IndexCollection (IndexCollection.java:662) - Additional fields to index: []
2024-06-19 10:54:58,875 INFO  [main] index.IndexCollection (IndexCollection.java:663) - Optimize (merge segments)? false
2024-06-19 10:54:58,875 INFO  [main] index.IndexCollection (IndexCollection.java:664) - Whitelist: null
2024-06-19 10:54:58,875 INFO  [main] index.IndexCollection (IndexCollection.java:665) - Pretokenized?: false
2024-06-19 10:54:58,875 INFO  [main] index.IndexCollection (IndexCollection.java:685) - Directly building Lucene indexes...
2024-06-19 10:54:58,875 INFO  [main] index.IndexCollection (IndexCollection.java:686) - Index path: indexes_100k
2024-06-19 10:54:58,876 INFO  [main] index.IndexCollection (IndexCollection.java:741) - ============ Indexing Collection ============
2024-06-19 10:54:58,986 INFO  [main] index.IndexCollection (IndexCollection.java:845) - Thread pool with 1 threads initialized.
2024-06-19 10:54:58,986 INFO  [main] index.IndexCollection (IndexCollection.java:847) - Initializing collection in resources_100k
2024-06-19 10:54:58,987 INFO  [main] index.IndexCollection (IndexCollection.java:856) - 0 files found
2024-06-19 10:54:58,987 INFO  [main] index.IndexCollection (IndexCollection.java:857) - Starting to index...
2024-06-19 10:54:58,996 INFO  [main] index.IndexCollection (IndexCollection.java:941) - Indexing Complete! 0 documents indexed
2024-06-19 10:54:58,996 INFO  [main] index.IndexCollection (IndexCollection.java:942) - ============ Final Counter Values ============
2024-06-19 10:54:58,996 INFO  [main] index.IndexCollection (IndexCollection.java:943) - indexed:                0
2024-06-19 10:54:58,996 INFO  [main] index.IndexCollection (IndexCollection.java:944) - unindexable:            0
2024-06-19 10:54:58,996 INFO  [main] index.IndexCollection (IndexCollection.java:945) - empty:                  0
2024-06-19 10:54:58,996 INFO  [main] index.IndexCollection (IndexCollection.java:946) - skipped:                0
2024-06-19 10:54:58,997 INFO  [main] index.IndexCollection (IndexCollection.java:947) - errors:                 0
2024-06-19 10:54:58,999 INFO  [main] index.IndexCollection (IndexCollection.java:950) - Total 0 documents indexed in 00:00:00
Downloading 50 example human trajectories...
Downloading example trajectories complete
Collecting typing_extensions<4.6.0
  Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
Collecting gym==0.23.1
  Using cached gym-0.23.1-py3-none-any.whl
Requirement already satisfied: numpy>=1.18.0 in /home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages (from gym==0.23.1) (1.22.4)
Requirement already satisfied: cloudpickle>=1.2.0 in /home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages (from gym==0.23.1) (3.0.0)
Requirement already satisfied: gym-notices>=0.0.4 in /home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages (from gym==0.23.1) (0.0.8)
Requirement already satisfied: importlib-metadata>=4.10.0 in /home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages (from gym==0.23.1) (7.1.0)
Requirement already satisfied: zipp>=0.5 in /home/joaoabrantis/miniconda3/envs/agentenv-webshop/lib/python3.8/site-packages (from importlib-metadata>=4.10.0->gym==0.23.1) (3.19.2)
Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Installing collected packages: typing_extensions, gym
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.12.2
    Uninstalling typing_extensions-4.12.2:
      Successfully uninstalled typing_extensions-4.12.2
  Attempting uninstall: gym
    Found existing installation: gym 0.24.0
    Uninstalling gym-0.24.0:
      Successfully uninstalled gym-0.24.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.110.3 requires typing-extensions>=4.8.0, but you have typing-extensions 4.5.0 which is incompatible.
Successfully installed gym-0.23.1 typing_extensions-4.5.0
DEPRECATION: https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.3.0/en_core_web_lg-3.3.0-py3-none-any.whl#egg=en_core_web_lg==3.3.0 contains an egg fragment with a non-PEP 508 name pip 25.0 will enforce this behaviour change. A possible replacement is to use the req @ url syntax, and remove the egg fragment. Discussion can be found at https://github.com/pypa/pip/issues/11617
```
</details>

**Comment by Yiwen-Ding** [comment]
Hi,

Thank you for reporting this issue. It might be caused by an incompatible version of NumPy. Could you try running the following command to see if it fixes the problem?
`pip uninstall numpy && pip install numpy`
