### ISSUE TITLE
agentenv-sqlgym环境配置错误

### ISSUE THREAD

**Issue by shuishiwojiade** [WooooDyy/AgentGym#28]
您好，当我配置agentenv-sqlgym环境时遇到错误，无法解决：
pkg_info.replace_header("Metadata-Version", "2.1")
KeyError：'metadata-version'

详细信息如下：
Building wheels for collected packages: agentenv_sqlgym
  Building wheel for agentenv_sqlgym (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for agentenv_sqlgym (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running bdist_wheel
      running build
      running build_py
      running egg_info
      writing agentenv_sqlgym.egg-info/PKG-INFO
      writing dependency_links to agentenv_sqlgym.egg-info/dependency_links.txt
      writing entry points to agentenv_sqlgym.egg-info/entry_points.txt
      writing requirements to agentenv_sqlgym.egg-info/requires.txt
      writing top-level names to agentenv_sqlgym.egg-info/top_level.txt
      reading manifest file 'agentenv_sqlgym.egg-info/SOURCES.txt'
      writing manifest file 'agentenv_sqlgym.egg-info/SOURCES.txt'
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      running install_egg_info
Copying agentenv_sqlgym.egg-info to build/bdist.linux-x86_64/wheel/agentenv_sqlgym-0.0.1-py3.8.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "/root/miniforge3/envs/agentenv-sqlgym/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/miniforge3/envs/agentenv-sqlgym/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/miniforge3/envs/agentenv-sqlgym/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 106, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/command/bdist_wheel.py", line 425, in run
          self.egg2dist(self.egginfo_dir, distinfo_dir)
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/command/bdist_wheel.py", line 563, in egg2dist
          pkg_info = pkginfo_to_metadata(egginfo_path, pkginfo_path)
        File "/tmp/pip-build-env-p6enm782/overlay/lib/python3.8/site-packages/setuptools/_vendor/wheel/metadata.py", line 150, in pkginfo_to_metadata
          pkg_info.replace_header("Metadata-Version", "2.1")
        File "/root/miniforge3/envs/agentenv-sqlgym/lib/python3.8/email/message.py", line 558, in replace_header
          raise KeyError(_name)
      KeyError: 'metadata-version'

**Comment by shuishiwojiade** [comment]
直接conda install python以及指定python版本为3.8都会有这个错误

**Comment by xingjianleng** [comment]
Have you tried using a different version of Python? If you run `conda install python` after creating your conda environment, it will update the Python version to the latest 3.12. Although Python 3.12 might seem too new, it has been working fine for me.

**Comment by shuishiwojiade** [comment]
> Have you tried using a different version of Python? If you run `conda install python` after creating your conda environment, it will update the Python version to the latest 3.12. Although Python 3.12 might seem too new, it has been working fine for me.

使用conda install python后版本是3.12，但错误仍未消除

**Comment by xingjianleng** [comment]
That's weird... I thought about a workaround and prepared this dockerfile for building a docker version of the `sqlgym` environment.

```dockerfile
# Use a base image that has Conda installed, such as ContinuumIO's Miniconda3 image
FROM continuumio/miniconda3

# Install the unzip package
RUN apt-get update && apt-get install -y \
    unzip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /app

# Copy the rest of the application code
COPY . /app/

# Create the conda environment
RUN conda create --name agentenv-sqlgym -y

# Set the environment variables
ENV PATH=/opt/conda/envs/agentenv-sqlgym/bin:$PATH
ENV CONDA_DEFAULT_ENV=agentenv-sqlgym

# Activate the conda environment
SHELL ["conda", "run", "-n", "agentenv-sqlgym", "/bin/bash", "-c"]

# Follow the original instruction, install python here
RUN conda install python

# Install the agentenv-sqlgym package
RUN pip install -e .

# Run the setup script
RUN bash setup.sh

# Cleanup cache
RUN conda clean -ya
RUN pip cache purge

# Expose the port that the sqlgym service will run on
EXPOSE 36002

# Define additional environment variable for the bird path
ENV AGENTENV_SQLGYM_BIRD_PATH=./bird

# Command to run the sqlgym application
CMD ["conda", "run", "--no-capture-output", "-n", "agentenv-sqlgym", "sqlgym", "--host", "0.0.0.0", "--port", "36002"]
```

You can save the above code to `AgentGym/agentenv-sqlgym/Dockerfile` and change your working directory to this folder. Then run `docker build -t agentenv-sqlgym .` to build the image. After that, you can run the environment via `docker run -d -p {PORT}:36002 agentenv-sqlgym`, where {PORT} is a free port on your machine.

**Comment by xingjianleng** [comment]
One more thing to add, for the `AgentGym/agentenv-sqlgym/setup.sh`, you may need to make the following change as the bird bench made some modifications to their dev split dataset.

```shell
wget -c https://bird-bench.oss-cn-beijing.aliyuncs.com/dev.zip
unzip dev.zip
mv dev_20240627 dev  # <--- After 20240627, the dev set name is updated
cd dev
unzip dev_databases.zip
```
